$ANSIBLE_VAULT;1.1;AES256
39346434386130663837643732363134383539393836623164303038653464353136653930383737
3665646534336539306232323134306562303461316634660a343238666530643166633165626134
62343438313266643036393232363830333132633136663062336164383966396633313632323437
3762626465646530320a623337643235323333653937663863363465313739323062626636643234
31303632336565616130363634323266613431393838653862383066373439383061313632663135
32656261643432643738336138346236646433333230653839333564303435376334313465356134
36623965613737363136643738616362343665653261653731303663383530316563346139333064
33656363303238373262363933616137636630626236306138346164303864353561326431316630
6138
